assess_runs: 5
aux_data: mnist
buffer_iter: 1000
buffer_size: 5000
buffer_wd: 0.001
ce_loss: false
run_id: 1

experiment_scenario: 1
cpus_per_job: 3
cuda: true
dataroot: /chiara
datasets: split_mnist, USPS
debug: true
early_stopping: 3
experiment_scenario: 1
fixed: false
gpus_per_job: 0.5
init_from_expert: false
loss_type: mse
lr: 0.01
max_cpus: 30
max_gpus: 4
metric_name: Top1_Acc_Stream/eval_phase/train_stream/Task000
model: lenet
multi: false
n_classes_node: 2
n_domains: 2
n_nodes: 10
num_classes: 10
num_iter_per_exp: 1000
pret: multi_digit
peval_on_test: true
random: false
reset_model: false
scenario: multi_digit
train_epochs: 10
train_mb_size: 128